# Generated by Django 4.2.20 on 2025-05-07 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_salles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('duree_seance', models.PositiveIntegerField(help_text='Durée en minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)], verbose_name='Durée de la séance')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/', verbose_name='Image')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('niveau_requis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports', to='gestion_activites.niveau', verbose_name='Niveau requis')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi'), ('DIM', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='gestion_salles.salle', verbose_name='Salle')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='gestion_activites.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'unique_together': {('sport', 'jour', 'heure_debut', 'salle')},
            },
        ),
    ]
