# Generated by Django 4.2.20 on 2025-05-07 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='capacite_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='duree_seance',
            field=models.PositiveIntegerField(help_text='Durée en minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Durée de la séance'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix'),
        ),
    ]
