# Generated by Django 4.2.20 on 2025-05-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_membres', '0002_alter_membre_options_remove_membre_niveau_and_more'),
        ('gestion_activites', '0002_alter_sport_capacite_max_alter_sport_duree_seance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_sport', to='gestion_membres.membre', verbose_name='Membre')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_sport', to='gestion_activites.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Inscription à un sport',
                'verbose_name_plural': 'Inscriptions aux sports',
                'unique_together': {('membre', 'sport', 'date_debut', 'date_fin')},
            },
        ),
    ]
