# Generated by Django 4.2.20 on 2025-05-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salles', '0001_initial'),
        ('gestion_coachs', '0001_initial'),
        ('gestion_activites', '0003_inscriptionsport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('places_disponibles', models.PositiveIntegerField(default=0, verbose_name='Places disponibles')),
                ('instructeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='gestion_coachs.coach', verbose_name='Instructeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='gestion_salles.salle', verbose_name='Salle')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='gestion_activites.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('sport', 'date', 'heure_debut', 'salle')},
            },
        ),
    ]
