# Generated by Django 4.2.20 on 2025-05-07 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_activites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(help_text="Années d'expérience", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expérience')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coachs/', verbose_name='Photo')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('specialites', models.ManyToManyField(related_name='coachs', to='gestion_activites.sport', verbose_name='Spécialités')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coachs',
            },
        ),
    ]
