# Generated by Django 4.2.20 on 2025-05-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_activites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/', verbose_name='Photo')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.niveau', verbose_name='Niveau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion_membres.membre', verbose_name='Membre')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion_activites.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('membre', 'sport')},
            },
        ),
    ]
