# Generated by Django 4.2.20 on 2025-05-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={},
        ),
        migrations.RemoveField(
            model_name='membre',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='photo',
        ),
        migrations.AlterField(
            model_name='membre',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membre',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
