# Generated by Django 4.2.20 on 2025-05-07 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('capacite', models.PositiveIntegerField(help_text='Nombre maximum de personnes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('description', models.TextField(verbose_name='Description')),
                ('superficie', models.PositiveIntegerField(help_text='Superficie en m²', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Superficie')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='gestion_salles.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
    ]
