# Generated by Django 5.0.2 on 2025-05-26 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_activites', '0004_seance'),
        ('gestion_membres', '0002_alter_membre_options_remove_membre_niveau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée'), ('EN_ATTENTE', 'En attente')], default='CONFIRMEE', max_length=20, verbose_name='Statut')),
                ('present', models.BooleanField(default=False, verbose_name='Présent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion_membres.membre', verbose_name='Membre')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion_activites.seance', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
                'unique_together': {('membre', 'seance')},
            },
        ),
    ]
